name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # ✅ FIX HERE
    - name: Restore dependencies
      run: dotnet restore CampusTouch.sln

    - name: Build project
      run: dotnet build CampusTouch.sln --no-restore --configuration Release

    - name: Run Tests 🔥
      run: dotnet test CampusTouch.sln --no-build --verbosity normal